package:
   name: intake-xarray
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake
    - python
    - scipy
    - xarray

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test --verbose

about:
  home: https://github.com/ContinuumIO/intake-xarray
  license: BSD
  license_file: LICENSE
  summary: |
    xarray plugins for Intake
