name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - intake>=0.4.1
  - xarray=0.11.0  # pinnned this low as a test
  - zarr
  - pytest
  - netcdf4
  - pydap
  - rasterio
  - scikit-image
