name: test_env
channels:
  - conda-forge
dependencies:
  - python
  - aiohttp
  - fsspec
  - gcsfs
  - h5netcdf
  - intake
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - s3fs
  - scikit-image
  - xarray
  - zarr
