name: test_env
channels:
  - conda-forge
dependencies:
  - python
  - aiohttp
  - h5netcdf
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - scikit-image
  - zarr
  - pip:
       - git+https://github.com/intake/filesystem_spec.git
       - git+https://github.com/intake/intake.git
       - git+https://github.com/pydata/xarray.git
       - rangehttpserver
