name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - aiohttp
  - h5netcdf
  - intake
  - netcdf4
  - pip
  - pydap
  - pytest
  - rasterio
  - scikit-image
  - xarray
  - zarr
  - pip:
       - rangehttpserver
