name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.CONDA_ENV }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [36, 36-defaults, 37-nodefaults]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test_env
          environment-file: ci/environment-py${{ matrix.CONDA_ENV }}.yml

      - name: Development Install Intake-Xarray
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          conda list

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose
